// ─── Shell Icon Overlay Implementation ────────────────────────────────────
//
// Implements `IShellIconOverlayIdentifier` to show sync status icons on
// files managed by gDriver in Windows Explorer.
//
// Five overlay states:
//   - cloud_only: Gray cloud (file is only in the cloud)
//   - syncing: Blue spinning arrow (file is being synced)
//   - synced/cached/offline: Green checkmark (file is synced)
//   - error: Red X (sync error)
//   - uploading: Blue up arrow (file is being uploaded)

#![allow(non_snake_case)]

use windows::{core::*, Win32::UI::Shell::*};

use crate::ipc;

// ─── Overlay CLSIDs ────────────────────────────────────────────────────────

pub const CLSID_CLOUD: GUID = GUID::from_u128(0xA1B2C3D4_1111_2222_3333_444455556601);
pub const CLSID_SYNCING: GUID = GUID::from_u128(0xA1B2C3D4_1111_2222_3333_444455556602);
pub const CLSID_SYNCED: GUID = GUID::from_u128(0xA1B2C3D4_1111_2222_3333_444455556603);
pub const CLSID_ERROR: GUID = GUID::from_u128(0xA1B2C3D4_1111_2222_3333_444455556604);
pub const CLSID_UPLOADING: GUID = GUID::from_u128(0xA1B2C3D4_1111_2222_3333_444455556605);

// ─── Overlay priority constants ────────────────────────────────────────────

const PRIORITY_SYNCING: i32 = 0;
const PRIORITY_UPLOADING: i32 = 0;
const PRIORITY_ERROR: i32 = 1;
const PRIORITY_CLOUD: i32 = 2;
const PRIORITY_SYNCED: i32 = 3;

// ─── Icon Overlay Implementations ──────────────────────────────────────────

/// Helper: check if a sync state matches the overlay type.
fn should_apply(overlay: &str, sync_state: &str) -> bool {
    match overlay {
        "cloud_only" => sync_state == "cloud_only",
        "syncing" => {
            sync_state == "syncing" || sync_state == "downloading" || sync_state == "uploading"
        }
        "synced" => sync_state == "synced" || sync_state == "cached" || sync_state == "offline",
        "error" => sync_state == "error",
        "uploading" => sync_state == "uploading",
        _ => false,
    }
}

/// Helper: get the icon resource path for an overlay type.
fn icon_path(overlay: &str) -> &'static str {
    match overlay {
        "cloud_only" => "gdriver_overlay_cloud.dll,-101",
        "syncing" => "gdriver_overlay_syncing.dll,-102",
        "synced" => "gdriver_overlay_synced.dll,-103",
        "error" => "gdriver_overlay_error.dll,-104",
        "uploading" => "gdriver_overlay_uploading.dll,-105",
        _ => "",
    }
}

/// Macro to implement IShellIconOverlayIdentifier for each overlay state.
/// The trait must be implemented on the `_Impl` wrapper type generated by
/// the `#[implement]` macro (windows-rs 0.58 convention).
macro_rules! impl_overlay {
    ($name:ident, $state:expr, $priority:expr) => {
        #[implement(IShellIconOverlayIdentifier)]
        #[derive(Default)]
        pub struct $name;

        impl $name {
            fn check_overlay_impl(overlay: &str, path: &PCWSTR) -> Result<()> {
                let path_str = unsafe { path.to_string().unwrap_or_default() };
                if let Some(state) = ipc::get_sync_state(&path_str) {
                    let sync_state = state
                        .get("state")
                        .and_then(|s| s.as_str())
                        .unwrap_or("unknown");
                    if should_apply(overlay, sync_state) {
                        return Ok(());
                    }
                }
                Err(Error::from_hresult(HRESULT(1)))
            }

            fn get_overlay_info_impl(
                overlay: &str,
                pwszIconFile: PWSTR,
                cchMax: i32,
                pIndex: *mut i32,
                pdwFlags: *mut u32,
            ) -> Result<()> {
                let path = icon_path(overlay);
                let wide: Vec<u16> = path.encode_utf16().chain(std::iter::once(0)).collect();
                let len = wide.len().min(cchMax as usize);
                unsafe {
                    std::ptr::copy_nonoverlapping(wide.as_ptr(), pwszIconFile.0 as *mut u16, len);
                    *pIndex = 0;
                    *pdwFlags = 0;
                }
                Ok(())
            }
        }
    };
}

// Generate overlay structs
impl_overlay!(CloudOverlay, "cloud_only", PRIORITY_CLOUD);
impl_overlay!(SyncingOverlay, "syncing", PRIORITY_SYNCING);
impl_overlay!(SyncedOverlay, "synced", PRIORITY_SYNCED);
impl_overlay!(ErrorOverlay, "error", PRIORITY_ERROR);
impl_overlay!(UploadingOverlay, "uploading", PRIORITY_UPLOADING);

// Implement the trait on each _Impl wrapper type.
// In windows-rs 0.58, the `#[implement]` macro generates a `Foo_Impl` wrapper
// and the COM vtable callbacks dispatch through that wrapper.

impl IShellIconOverlayIdentifier_Impl for CloudOverlay_Impl {
    fn IsMemberOf(&self, path: &PCWSTR, _attributes: u32) -> Result<()> {
        CloudOverlay::check_overlay_impl("cloud_only", path)
    }
    fn GetOverlayInfo(
        &self,
        pwszIconFile: PWSTR,
        cchMax: i32,
        pIndex: *mut i32,
        pdwFlags: *mut u32,
    ) -> Result<()> {
        CloudOverlay::get_overlay_info_impl("cloud_only", pwszIconFile, cchMax, pIndex, pdwFlags)
    }
    fn GetPriority(&self) -> Result<i32> {
        Ok(PRIORITY_CLOUD)
    }
}

impl IShellIconOverlayIdentifier_Impl for SyncingOverlay_Impl {
    fn IsMemberOf(&self, path: &PCWSTR, _attributes: u32) -> Result<()> {
        SyncingOverlay::check_overlay_impl("syncing", path)
    }
    fn GetOverlayInfo(
        &self,
        pwszIconFile: PWSTR,
        cchMax: i32,
        pIndex: *mut i32,
        pdwFlags: *mut u32,
    ) -> Result<()> {
        SyncingOverlay::get_overlay_info_impl("syncing", pwszIconFile, cchMax, pIndex, pdwFlags)
    }
    fn GetPriority(&self) -> Result<i32> {
        Ok(PRIORITY_SYNCING)
    }
}

impl IShellIconOverlayIdentifier_Impl for SyncedOverlay_Impl {
    fn IsMemberOf(&self, path: &PCWSTR, _attributes: u32) -> Result<()> {
        SyncedOverlay::check_overlay_impl("synced", path)
    }
    fn GetOverlayInfo(
        &self,
        pwszIconFile: PWSTR,
        cchMax: i32,
        pIndex: *mut i32,
        pdwFlags: *mut u32,
    ) -> Result<()> {
        SyncedOverlay::get_overlay_info_impl("synced", pwszIconFile, cchMax, pIndex, pdwFlags)
    }
    fn GetPriority(&self) -> Result<i32> {
        Ok(PRIORITY_SYNCED)
    }
}

impl IShellIconOverlayIdentifier_Impl for ErrorOverlay_Impl {
    fn IsMemberOf(&self, path: &PCWSTR, _attributes: u32) -> Result<()> {
        ErrorOverlay::check_overlay_impl("error", path)
    }
    fn GetOverlayInfo(
        &self,
        pwszIconFile: PWSTR,
        cchMax: i32,
        pIndex: *mut i32,
        pdwFlags: *mut u32,
    ) -> Result<()> {
        ErrorOverlay::get_overlay_info_impl("error", pwszIconFile, cchMax, pIndex, pdwFlags)
    }
    fn GetPriority(&self) -> Result<i32> {
        Ok(PRIORITY_ERROR)
    }
}

impl IShellIconOverlayIdentifier_Impl for UploadingOverlay_Impl {
    fn IsMemberOf(&self, path: &PCWSTR, _attributes: u32) -> Result<()> {
        UploadingOverlay::check_overlay_impl("uploading", path)
    }
    fn GetOverlayInfo(
        &self,
        pwszIconFile: PWSTR,
        cchMax: i32,
        pIndex: *mut i32,
        pdwFlags: *mut u32,
    ) -> Result<()> {
        UploadingOverlay::get_overlay_info_impl("uploading", pwszIconFile, cchMax, pIndex, pdwFlags)
    }
    fn GetPriority(&self) -> Result<i32> {
        Ok(PRIORITY_UPLOADING)
    }
}
